// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"GO-GOLF-API/internal/controller"
	"GO-GOLF-API/internal/repo"
	"GO-GOLF-API/internal/service/impl"
)

// Injectors from user.wire.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	iUserRepository := repo.NewUserRepository()
	iUserService := impl.NewUserService(iUserRepository)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
